service: serverless-obfuscator
app: obfuscator
tenant: albertnis

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  server:
    handler: src/functions/server/dist/server.server
    events:
      - http:
          path: /
          method: get
          cors: true
  translate:
    handler: src/functions/translate/translate.translate
    events:
      - http:
          path: translate
          method: get
          cors: true

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'