service: serverless-obfuscator
app: obfuscator
tenant: albertnis

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  server:
    handler: project/functions/server/index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  translate:
    handler: project/functions/translate/handler.translate
    events:
      - http:
          path: translate
          method: get
          cors: true

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'